name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2
  HUSKY: 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: ./.github/actions/setup

      - run: bun run lint

  test:
    name: Run unit tests (Node.js ${{ matrix.node_version }}; React ${{ matrix.react_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]
        react_version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: ./.github/actions/setup
      - run: mise use node@${{ matrix.node_version }}
      
      - name: Run tests
        run: REACT_VERSION=${{ matrix.react_version }} bun run test

  e2e-node:
    name: Run E2E tests (Node.js ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
      - run: mise use node@${{ matrix.node_version }}

      - name: Run E2E tests
        run: bun run --cwd e2e/node-esm run start
